branches:
  only:
  - master
  - /^v\d+\.\d+\.x$/
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.21.0
matrix:
  allow_failures:
    - rust: nightly
    - rust: 1.21.0
script:
  - |
    cd $CRATE
    if [ -z "$FEATURES" ] || [ "$FEATURES" = runtime ]; then
      cargo build --verbose --no-default-features --features=$FEATURES &&
      cargo test --verbose --no-default-features --features=$FEATURES
    else
      cargo check --verbose --no-default-features --features=$FEATURES
    fi
env:
  - CRATE=twitter-stream FEATURES=runtime
  - CRATE=twitter-stream FEATURES=runtime,tls
#  - CRATE=twitter-stream FEATURES=runtime,tls-rustls
  - CRATE=twitter-stream FEATURES=runtime,tls-openssl
  - CRATE=twitter-stream FEATURES=runtime,egg-mode,tweetust
  - CRATE=twitter-stream-message
